# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:11.11.0

pipelines:
  default:
    - step:
        name: setup and build
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run build
        artifacts:
          - dist/**
    - step:
        name: deploy
        script:
          - echo $FIREBASE_TOKEN
          - pipe: atlassian/firebase-deploy:0.2.0
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN
              PROJECT_ID: "atmos-10"

