name: atmos-angular
run-name: atmos-angular build and deploy by ${{ github.actor }}
on:
  push:
    paths:
      - "atmos-angular/**"
      - ".github/workflows/atmos-angular.yml"

env:
  BUILD_PATH: ./atmos-angular/dist/atmos
  ZIP_PATH: OwnaTechnical.Application/bin/publish/OwnaTechnical.zip

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./atmos-angular
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - run: npm install

      - run: npm run build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: atmos
          path: ${{ env.BUILD_PATH }}
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: atmos
          path: atmos

      - name: Deploy static site to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: projects.samhenry.tech
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_EXTERNALDEPLOYMENT_KEYID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_EXTERNALDEPLOYMENT_SECRET }}
          AWS_REGION: "ap-southeast-2"
          SOURCE_DIR: "./atmos"
          DEST_DIR: "atmos"
