name: github-actions
run-name: atmos deploy by ${{ github.actor }}
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./atmos-angular
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          
      - name: npm install
        run: npm install
        
      - run: npm run build
      
      - run: ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
      
      - name: Deploy static site to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: projects.samhenry.tech
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_EXTERNALDEPLOYMENT_KEYID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_EXTERNALDEPLOYMENT_SECRET }}
          AWS_REGION: 'ap-southeast-2'
          SOURCE_DIR: './atmos-angular/dist/atmos'
          DEST_DIR: 'atmos'
